import { describe, expect, it } from "vitest";
import { chooseAiAction } from "../src/game/ai";
import { createGame, gameReducer } from "../src/game/state";
import { cleanHalfBoard, cloneBoard, createBoard, evaluateBoard, legalSkill, legalTarget, nextSeed, skillUnavailableReason, winningLine } from "../src/game/rules";
import type { GameState, Player, Position } from "../src/game/types";

const stones = (positions: Position[], owner: Player = 0) => { const board = createBoard(); positions.forEach((p) => board[p.row][p.col] = { owner }); return board; };
const rich = (character: GameState["players"][0]["character"], opponent: GameState["players"][0]["character"] = "principal") => { const state = createGame({ mode: "local", playerCharacter: character, opponentCharacter: opponent, environment: false, seed: 42 }); state.players[0].energy = 6; state.players[1].energy = 6; return state; };

describe("传统五子棋底层规则", () => {
  it("1 横向五连", () => expect(winningLine(stones([0,1,2,3,4].map((col) => ({ row: 3, col }))), 0)).toHaveLength(5));
  it("2 纵向五连", () => expect(winningLine(stones([0,1,2,3,4].map((row) => ({ row, col: 3 }))), 0)).toHaveLength(5));
  it("3 主对角线五连", () => expect(winningLine(stones([0,1,2,3,4].map((n) => ({ row: n, col: n }))), 0)).toHaveLength(5));
  it("4 反对角线五连", () => expect(winningLine(stones([0,1,2,3,4].map((n) => ({ row: n, col: 8 - n }))), 0)).toHaveLength(5));
  it("5 超过五颗仍然获胜", () => expect(winningLine(stones([0,1,2,3,4,5].map((col) => ({ row: 9, col }))), 0)).toHaveLength(6));
  it("6 半子不计入五连", () => { const board = stones([0,1,2,3].map((col) => ({ row: 2, col }))); board[2][4] = { owner: 0, half: true }; expect(winningLine(board, 0)).toBeNull(); });
  it("7 半子转正后形成五连", () => { const board = stones([0,1,2,3,4].map((col) => ({ row: 2, col }))); expect(evaluateBoard(board)?.winner).toBe(0); });
  it("8 指定断线只影响对应连接", () => { const board = stones([0,1,2,3,4].map((col) => ({ row: 5, col }))); expect(winningLine(board, 0, [{row:5,col:2},{row:5,col:3}])).toBeNull(); expect(winningLine(board, 0, [{row:4,col:2},{row:4,col:3}])).toHaveLength(5); });
  it("9 双方同时五连判荒诞平局", () => { const board = stones([0,1,2,3,4].map((col) => ({ row: 1, col }))); [0,1,2,3,4].forEach((row) => board[row][9] = { owner: 1 }); expect(evaluateBoard(board)?.reason).toBe("absurdDraw"); });
});

describe("物理技能 2.0", () => {
  it("10 飞沙走石可移除任意合法敌子", () => { let state = rich("principal", "ziqi"); state.board[7][7] = { owner: 1 }; state = gameReducer(state, { type: "SELECT_SKILL", skillId: "flyingStone" }); state = gameReducer(state, { type: "SKILL_TARGET", position: { row: 7, col: 7 } }); expect(state.board[7][7]).toBeNull(); expect(state.removed.at(-1)?.cause).toBe("flyingStone"); });
  it("11 飞沙走石不能选择受保护棋子", () => { const state = rich("principal", "ziqi"); state.board[7][7] = { owner: 1, protected: true }; expect(legalTarget(state, 0, "flyingStone", { row: 7, col: 7 })).toBe(false); });
  it("12 擒拿在飞沙走石时进入反制窗口", () => { let state = rich("principal", "zhang"); state.board[7][7] = { owner: 1 }; state = gameReducer(state, { type: "SELECT_SKILL", skillId: "flyingStone" }); state = gameReducer(state, { type: "SKILL_TARGET", position: { row: 7, col: 7 } }); expect(state.phase).toBe("reactionWindow"); expect(state.pendingSkill?.reactionSkillId).toBe("grapple"); });
  it("13 擒拿阻止移除并锁定飞沙走石", () => { let state = rich("principal", "zhang"); state.board[7][7] = { owner: 1 }; state = gameReducer(state, { type: "SELECT_SKILL", skillId: "flyingStone" }); state = gameReducer(state, { type: "SKILL_TARGET", position: { row: 7, col: 7 } }); state = gameReducer(state, { type: "REACTION", use: true }); expect(state.board[7][7]).not.toBeNull(); expect(state.players[0].lockedSkills.flyingStone).toBe(2); expect(state.players[1].usedSkills).toContain("grapple"); });
  it("14 被擒拿后攻击者仍消耗飞沙走石资源", () => { let state = rich("principal", "zhang"); state.board[7][7] = { owner: 1 }; state = gameReducer(state, { type: "SELECT_SKILL", skillId: "flyingStone" }); state = gameReducer(state, { type: "SKILL_TARGET", position: { row: 7, col: 7 } }); state = gameReducer(state, { type: "REACTION", use: true }); expect(state.players[0].energy).toBe(3); expect(state.players[0].usedSkills).toContain("flyingStone"); });
  it("15 静如止水冻结操作但不吞回合", () => { let state = rich("ziqi", "principal"); state = gameReducer(state, { type: "SELECT_SKILL", skillId: "stillWater" }); expect(state.phase).toBe("skippingTurn"); expect(state.current).toBe(1); expect(state.freezeUntil).not.toBeNull(); state = gameReducer(state, { type: "END_FREEZE" }); expect(state.phase).toBe("playerTurn"); expect(state.current).toBe(1); });
  it("16 静如止水每局可以使用两次", () => { let state = rich("ziqi", "principal"); state = gameReducer(state, { type: "SELECT_SKILL", skillId: "stillWater" }); state = gameReducer(state, { type: "END_FREEZE" }); state.current = 0; state.phase = "playerTurn"; state.players[0].energy = 6; expect(legalSkill(state, 0, "stillWater")).toBe(true); });
  it("17 时光倒流恢复上一行动前棋盘", () => { let state = rich("zhang", "principal"); state = gameReducer(state, { type: "PLACE", position: { row: 7, col: 7 } }); expect(state.board[7][7]).not.toBeNull(); state.current = 0; state.phase = "playerTurn"; state.players[0].energy = 6; state = gameReducer(state, { type: "SELECT_SKILL", skillId: "timeRewind" }); expect(state.board[7][7]).toBeNull(); expect(state.players[0].usedSkills).toContain("timeRewind"); });
  it("18 梅开二度连续放置两颗棋子", () => { let state = rich("ziqi"); state = gameReducer(state, { type: "SELECT_SKILL", skillId: "doubleBloom" }); state = gameReducer(state, { type: "SKILL_TARGET", position: { row: 7, col: 7 } }); state = gameReducer(state, { type: "SKILL_TARGET", position: { row: 7, col: 8 } }); expect(state.board[7][7]?.owner).toBe(0); expect(state.board[7][8]?.owner).toBe(0); });
  it("19 保洁上门使用固定种子清除一半", () => { const board = createBoard(); for (let i = 0; i < 10; i++) board[7][i] = { owner: (i % 2) as Player }; const a = cleanHalfBoard(board, 123), b = cleanHalfBoard(board, 123); expect(a).toEqual(b); expect(a.removed).toHaveLength(5); });
  it("20 保洁上门会同时清除双方棋子", () => { const board = createBoard(); for (let i = 0; i < 6; i++) { board[5][i] = { owner: 0 }; board[9][i] = { owner: 1 }; } const cleaned = cleanHalfBoard(board, 456); expect(new Set(cleaned.removed.map((item) => item.stone.owner))).toEqual(new Set([0, 1])); expect(cleaned.removed.filter((item) => item.stone.owner === 0).length).toBeGreaterThan(0); expect(cleaned.removed.filter((item) => item.stone.owner === 1).length).toBeGreaterThan(0); });
  it("21 保洁不会清除受保护棋子", () => { const board = createBoard(); board[7][0] = { owner: 0, protected: true }; for (let i = 1; i < 8; i++) board[7][i] = { owner: (i % 2) as Player }; const cleaned = cleanHalfBoard(board, 123); expect(cleaned.board[7][0]?.protected).toBe(true); });
  it("21 力拔山兮在第8回合前不可用", () => { const state = rich("principal", "ziqi"); expect(skillUnavailableReason(state, 0, "mountain")).toContain("第8回合"); });
  it("22 力拔山兮无人补救时直接获胜", () => { let state = rich("principal", "zhang"); state.turn = 8; state.players[1].energy = 0; state = gameReducer(state, { type: "SELECT_SKILL", skillId: "mountain" }); expect(state.result?.reason).toBe("finisher"); expect(state.result?.finisher).toBe("mountain"); expect(state.boardCondition).toBe("broken"); });
  it("23 东山再起可阻止力拔山兮", () => { let state = rich("principal", "zhang"); state.turn = 8; state.board[7][7] = { owner: 1 }; state = gameReducer(state, { type: "SELECT_SKILL", skillId: "mountain" }); expect(state.pendingSkill?.reactionSkillId).toBe("comeback"); state = gameReducer(state, { type: "REACTION", use: true }); expect(state.result).toBeNull(); expect(state.board[7][7]).not.toBeNull(); expect(state.boardCondition).toBe("normal"); });
  it("24 调呈离山只对张呈生效", () => { const state = rich("ziqi", "principal"); state.turn = 8; expect(legalSkill(state, 0, "lure")).toBe(false); });
  it("25 调呈离山无人倒流时终结棋局", () => { let state = rich("ziqi", "zhang"); state.turn = 8; state.players[1].energy = 0; state = gameReducer(state, { type: "SELECT_SKILL", skillId: "lure" }); expect(state.result?.finisher).toBe("lure"); });
  it("26 时光倒流可反制调呈离山", () => { let state = rich("ziqi", "zhang"); state.turn = 8; state = gameReducer(state, { type: "SELECT_SKILL", skillId: "lure" }); expect(state.pendingSkill?.reactionSkillId).toBe("timeRewind"); state = gameReducer(state, { type: "REACTION", use: true }); expect(state.result).toBeNull(); expect(state.players[1].usedSkills).toContain("timeRewind"); });
  it("27 两极反转需要80快乐值", () => { const state = rich("principal", "zhang"); state.turn = 8; state.happy = 79; expect(legalSkill(state, 0, "finalReverse")).toBe(false); state.happy = 80; expect(legalSkill(state, 0, "finalReverse")).toBe(true); });
  it("28 两极反转无反制时直接获胜", () => { let state = rich("principal", "zhang"); state.turn = 8; state.happy = 80; state.players[1].energy = 0; state = gameReducer(state, { type: "SELECT_SKILL", skillId: "finalReverse" }); expect(state.result?.finisher).toBe("finalReverse"); });
  it("29 取消目标选择不消耗技能值", () => { let state = rich("principal", "ziqi"), energy = state.players[0].energy; state.board[7][7] = { owner: 1 }; state = gameReducer(state, { type: "SELECT_SKILL", skillId: "flyingStone" }); state = gameReducer(state, { type: "CANCEL_SKILL" }); expect(state.players[0].energy).toBe(energy); });
});

describe("状态机与AI", () => {
  it("30 自由对战保留双方独立角色选择", () => { const state = createGame({ mode: "free", playerCharacter: "wang", opponentCharacter: "ziqi" }); expect(state.players[0].character).toBe("wang"); expect(state.players[1].character).toBe("ziqi"); });
  it("31 固定种子产生相同序列", () => expect(nextSeed(12345)).toBe(nextSeed(12345)));
  it("32 游戏结束后不能继续落子", () => { let state = rich("zhang"); state.result = { winner: 0, reason: "five" }; const before = cloneBoard(state.board); state = gameReducer(state, { type: "PLACE", position: { row: 7, col: 7 } }); expect(state.board).toEqual(before); });
  it("33 AI会完成一步直接获胜", () => { const state = rich("principal"); state.current = 1; [3,4,5,6].forEach((c) => state.board[4][c] = { owner: 1 }); const action = chooseAiAction(state), board = cloneBoard(state.board); board[action.position!.row][action.position!.col] = { owner: 1 }; expect(evaluateBoard(board)?.winner).toBe(1); });
  it("34 AI会阻挡对方下一步获胜", () => { const state = rich("principal"); state.current = 1; [3,4,5,6].forEach((c) => state.board[4][c] = { owner: 0 }); const action = chooseAiAction(state); expect([{row:4,col:2},{row:4,col:7}]).toContainEqual(action.position); });
  it("35 重开清除冻结、快照与损坏状态", () => { let state = rich("zhang"); state.boardCondition = "broken"; state.freezeUntil = Date.now() + 5000; state.snapshots = [{ board: createBoard(), current: 0, turn: 1, lastMove: null, moveHistory: [], cutLine: null }]; state = gameReducer(state, { type: "RESTART" }); expect(state.boardCondition).toBe("normal"); expect(state.freezeUntil).toBeNull(); expect(state.snapshots).toHaveLength(0); });
  it("36 技能动画清除后仍可继续落子", () => { let state = rich("principal", "ziqi"); state.board[7][7] = { owner: 1 }; state = gameReducer(state, { type: "SELECT_SKILL", skillId: "flyingStone" }); state = gameReducer(state, { type: "SKILL_TARGET", position: { row: 7, col: 7 } }); state = gameReducer(state, { type: "CLEAR_ANIMATION" }); state = gameReducer(state, { type: "PLACE", position: { row: 0, col: 0 } }); expect(state.board[0][0]?.owner).toBe(1); });
  it("37 测试台可修改快乐值和双方技能值", () => { let state = rich("zhang", "ziqi"); state = gameReducer(state, { type: "DEBUG_SET", field: "happy", value: 88 }); state = gameReducer(state, { type: "DEBUG_SET", field: "blackEnergy", value: 4 }); state = gameReducer(state, { type: "DEBUG_SET", field: "whiteEnergy", value: 5 }); expect(state.happy).toBe(88); expect(state.players[0].energy).toBe(4); expect(state.players[1].energy).toBe(5); });
  it("38 测试台可切换行动方并清除临时状态", () => { let state = rich("zhang", "ziqi"); state.players[0].frozen = 1; state.boardCondition = "frozen"; state = gameReducer(state, { type: "DEBUG_SET_CURRENT", player: 1 }); expect(state.current).toBe(1); state = gameReducer(state, { type: "DEBUG_CLEAR_TEMP" }); expect(state.players[0].frozen).toBe(0); expect(state.boardCondition).toBe("normal"); });
});
