import { characters, reactionCards, skills } from "../game/config";
import { legalSkill, skillCost } from "../game/rules";
import type { GameAction, GameState } from "../game/types";
import { BoardCanvas } from "./BoardCanvas";
import { CharacterPanel } from "./CharacterPanel";

export function GameView({ state, dispatch, onHome }: { state: GameState; dispatch: React.Dispatch<GameAction>; onHome:()=>void }) {
  const active = state.players[state.current]; const char = characters.find((c)=>c.id===active.character)!; const reaction = reactionCards.find((r)=>r.id===state.players[state.pendingSkill ? (1-state.pendingSkill.player) as 0|1 : state.current].reaction)!; const winner = state.result?.winner;
  return <main className={`game-shell ${state.happyTimeTurns>0?"happy-time":""}`}>
    <div className="curtain left"/><div className="curtain right"/><div className="audience" aria-hidden="true">{Array.from({length:18},(_,i)=><i key={i}/>)}</div>
    <header className="game-top"><button onClick={onHome}>‹ 礼堂</button><div className="turn-display"><small>第 {Math.ceil(state.turn/2)} 回合</small><strong>{state.phase==="aiThinking"?"对手思考中":state.result?"棋局结束":`${char.name} 行动`}</strong></div><div className="happy-meter"><span>全场快乐值</span><div><i style={{width:`${state.happy}%`}}/></div><b>{state.happy}</b></div><div className="event-note"><small>最近播报</small><span>{state.statusText}</span></div></header>
    <section className="stage"><CharacterPanel state={state} player={0}/><div className={`board-wrap ${state.animation?"animating":""}`}><div className="crooked-banner">技能五子棋学校 <small>第 {state.chapter} 课堂</small></div>{state.dialogue&&<div className="dialogue"><b>{typeof state.dialogue.speaker === "string" ? state.dialogue.speaker : "系统"}</b><span>{state.dialogue.text}</span></div>}<BoardCanvas state={state} onCell={(position)=>dispatch(state.phase==="skillTargeting"||state.phase==="multiStepSkill"?{type:"SKILL_TARGET",position}:{type:"PLACE",position})}/>{state.phase==="aiThinking"&&<div className="thinking"><i/><span>{state.dialogue?.text ?? "正在计算五子棋的真谛。"}</span></div>}{state.phase==="reactionWindow"&&<div className="reaction-window"><small>反制窗口</small><h2>{reaction.name}</h2><p>{reaction.description}</p><div><button onClick={()=>dispatch({type:"REACTION",use:false})}>保持沉默</button><button onClick={()=>dispatch({type:"REACTION",use:true})}>立即反制</button></div></div>}</div><CharacterPanel state={state} player={1}/></section>
    <section className="control-deck"><div className="deck-label"><small>{state.mode==="pure"?"本模式谢绝技能":"当前角色技能"}</small><strong>{char.name} · {state.current===0?"黑棋":"白棋"}</strong></div><div className="skill-bar">{state.mode!=="pure"&&char.skills.map((id)=>{const s=skills[id],disabled=state.phase!=="playerTurn"||!legalSkill(state,state.current,id);return <button key={id} disabled={disabled} className={state.selectedSkill===id?"selected":""} onClick={()=>dispatch({type:"SELECT_SKILL",skillId:id})}><span>{s.name}</span><small>{s.blurb}</small><b>{skillCost(state,id)} 技能值</b>{(active.lockedSkills[id]??0)>0&&<em>✋ 被擒拿</em>}{active.usedSkills.includes(id)&&<em>本局已用</em>}</button>})}{state.mode==="pure"&&<div className="pure-message">据说有人只是想正常下棋。这里没有技能按钮，空气十分安静。</div>}</div>{(state.phase==="skillTargeting"||state.phase==="multiStepSkill")&&<button className="cancel-skill" onClick={()=>dispatch({type:"CANCEL_SKILL"})}>取消目标选择</button>}<div className="reaction-card"><small>反制卡</small><b>{reactionCards.find((r)=>r.id===active.reaction)?.name}</b><span>{active.reactionUsed?"已使用":"等待合适时机"}</span></div></section>
    {state.result&&<div className="result-overlay"><div className="result-card"><small>本局结算</small><h1>{winner===null?"荒诞平局":`${characters.find((c)=>c.id===state.players[winner ?? 0].character)?.name} 获胜`}</h1><p>{state.happyTriggered?"胜负已分，但大家好像更关心刚才那段舞。":"五连成立，规则在最后一刻保持了尊严。"}</p><dl><div><dt>回合数</dt><dd>{Math.ceil(state.turn/2)}</dd></div><div><dt>技能使用</dt><dd>{state.stats.skillUses}</dd></div><div><dt>成功反制</dt><dd>{state.stats.counters}</dd></div><div><dt>环境事件</dt><dd>{state.stats.events}</dd></div><div><dt>最高快乐</dt><dd>{state.stats.maxHappy}</dd></div></dl><div className="result-actions"><button onClick={onHome}>返回首页</button><button onClick={()=>dispatch({type:"RESTART"})}>再来一局</button></div></div></div>}
  </main>;
}
