import { characters, skills } from "../game/config";
import { legalSkill, skillCost, skillUnavailableReason, skillUseCount } from "../game/rules";
import type { GameAction, GameState } from "../game/types";
import { BoardCanvas } from "./BoardCanvas";
import { CharacterPanel } from "./CharacterPanel";
import { GameModifier } from "./GameModifier";

export function GameView({ state, dispatch, onHome }: { state: GameState; dispatch: React.Dispatch<GameAction>; onHome:()=>void }) {
  const active = state.players[state.current], char = characters.find((c)=>c.id===active.character)!, winner = state.result?.winner;
  const reactionId = state.pendingSkill?.reactionSkillId, reaction = reactionId ? skills[reactionId] : null;
  const equippedReaction = char.skills.find((id)=>skills[id].reactionOnly);
  const finisherText = state.result?.finisher === "mountain" ? "棋盘被摔坏，东山再起未能赶到。" : state.result?.finisher === "lure" ? "张呈已被物理调离山东。" : state.result?.finisher === "finalReverse" ? "黑历史投影完成了最后一击。" : "五连成立，规则在最后一刻保持了尊严。";
  return <main className={`game-shell ${state.happyTimeTurns>0?"happy-time":""} board-${state.boardCondition}`}>
    <div className="curtain left"/><div className="curtain right"/><div className="audience" aria-hidden="true">{Array.from({length:18},(_,i)=><i key={i}/>)}</div>
    <header className="game-top"><button onClick={onHome}>‹ 礼堂</button><div className="turn-display"><small>第 {Math.ceil(state.turn/2)} 回合</small><strong>{state.phase==="aiThinking"?"对手思考中":state.phase==="skippingTurn"?"时间冻结":state.result?"棋局结束":`${char.name} 行动`}</strong></div><div className="happy-meter"><span>全场快乐值</span><div><i style={{width:`${state.happy}%`}}/></div><b>{state.happy}</b></div><div className="event-note"><small>最近播报</small><span>{state.statusText}</span></div></header>
    <section className="stage"><CharacterPanel state={state} player={0}/><div className={`board-wrap ${state.animation||state.phase==="skippingTurn"?"animating":""}`}><div className="crooked-banner">技能五子棋学校 <small>物理技能 2.0</small></div>{state.dialogue&&<div className="dialogue"><b>{state.dialogue.speaker}</b><span>{state.dialogue.text}</span></div>}<BoardCanvas state={state} onCell={(position)=>dispatch(state.phase==="skillTargeting"||state.phase==="multiStepSkill"?{type:"SKILL_TARGET",position}:{type:"PLACE",position})}/>
      {state.phase==="aiThinking"&&<div className="thinking"><i/><span>{state.dialogue?.text ?? "正在计算哪条规则最容易摔。"}</span></div>}
      {state.phase==="skippingTurn"&&<div className="freeze-overlay"><b>❄ 静如止水</b><span>空气与棋盘操作冻结5秒</span><i/></div>}
      {state.phase==="reactionWindow"&&reaction&&<div className="reaction-window"><small>终结 / 反制窗口</small><h2>{reaction.name} · 就绪</h2><p>{reaction.blurb}</p><div><button onClick={()=>dispatch({type:"REACTION",use:false})}>放弃反制</button><button onClick={()=>dispatch({type:"REACTION",use:true})}>发动 {reaction.name}</button></div></div>}
    </div><CharacterPanel state={state} player={1}/></section>
    <section className="control-deck"><div className="deck-label"><small>{state.mode==="pure"?"本模式谢绝技能":"当前角色技能"}</small><strong>{char.name} · {state.current===0?"黑棋":"白棋"}</strong></div><div className="skill-bar">{state.mode!=="pure"&&char.skills.map((id)=>{const s=skills[id],reason=skillUnavailableReason(state,state.current,id),used=skillUseCount(state,state.current,id),disabled=state.phase!=="playerTurn"||!legalSkill(state,state.current,id);return <button key={id} disabled={disabled} className={`${state.selectedSkill===id?"selected ":""}${s.category}`} onClick={()=>dispatch({type:"SELECT_SKILL",skillId:id})}><span>{s.name}</span><small>{s.blurb}</small><b>{s.reactionOnly?used>=s.uses?"已使用":"就绪":s.finisher?`终极 · ${skillCost(state,id)}点`:`${skillCost(state,id)} 技能值`}</b>{reason&&<em>{reason}</em>}</button>})}{state.mode==="pure"&&<div className="pure-message">据说有人只是想正常下棋。这里没有技能按钮，空气十分安静。</div>}</div>{(state.phase==="skillTargeting"||state.phase==="multiStepSkill")&&<button className="cancel-skill" onClick={()=>dispatch({type:"CANCEL_SKILL"})}>取消目标选择</button>}<div className="reaction-card"><small>防御招式</small><b>{equippedReaction?skills[equippedReaction].name:"无"}</b><span>{equippedReaction?(skillUseCount(state,state.current,equippedReaction)>=skills[equippedReaction].uses?"已使用":"等待危机触发"):"靠职业素养防守"}</span></div></section>
    <GameModifier state={state} dispatch={dispatch}/>
    {state.result&&<div className="result-overlay"><div className="result-card"><small>{state.result.reason==="finisher"?"终结技结算":"本局结算"}</small><h1>{winner===null?"荒诞平局":`${characters.find((c)=>c.id===state.players[winner ?? 0].character)?.name} 获胜`}</h1><p>{state.happyTriggered?"胜负已分，但大家好像更关心刚才那段舞。":finisherText}</p><dl><div><dt>回合数</dt><dd>{Math.ceil(state.turn/2)}</dd></div><div><dt>技能使用</dt><dd>{state.stats.skillUses}</dd></div><div><dt>成功反制</dt><dd>{state.stats.counters}</dd></div><div><dt>环境事件</dt><dd>{state.stats.events}</dd></div><div><dt>最高快乐</dt><dd>{state.stats.maxHappy}</dd></div></dl><div className="result-actions"><button onClick={onHome}>返回首页</button><button onClick={()=>dispatch({type:"RESTART"})}>再来一局</button></div></div></div>}
  </main>;
}
