import { useEffect, useMemo, useReducer, useState } from "react";
import { characters, skillList, storyChapters } from "./game/config";
import { createGame, gameReducer } from "./game/state";
import type { AiDifficulty, CharacterId, GameMode } from "./game/types";
import { playTone, type SoundSettings } from "./audio";
import { Home, type HomeAction } from "./components/Home";
import { CharacterSelect } from "./components/CharacterSelect";
import { GameView } from "./components/GameView";

type Screen = "home" | "select" | "dialogue" | "game";
interface Settings extends SoundSettings { dialogue: boolean; reducedMotion: boolean }
const load = <T,>(key:string,fallback:T):T => { try { const value=localStorage.getItem(key); return value?JSON.parse(value):fallback; } catch { return fallback; } };

export default function App() {
  const [screen,setScreen]=useState<Screen>("home"), [mode,setMode]=useState<GameMode>("story"), [selected,setSelected]=useState<CharacterId>("zhang"), [difficulty,setDifficulty]=useState<AiDifficulty>("normal"), [environment,setEnvironment]=useState(true), [chaos,setChaos]=useState<"normal"|"extreme">("normal"), [chapter,setChapter]=useState(1), [dialogueIndex,setDialogueIndex]=useState(0), [modal,setModal]=useState<HomeAction|null>(null);
  const [settings,setSettings]=useState<Settings>(()=>load("skill-gomoku-settings",{enabled:true,volume:.7,dialogue:true,reducedMotion:false}));
  const [unlocked,setUnlocked]=useState(()=>load("skill-gomoku-progress",1));
  const initial=useMemo(()=>createGame({mode:"story",playerCharacter:"zhang",opponentCharacter:"ziqi"}),[]); const [game,dispatch]=useReducer(gameReducer,initial);
  useEffect(()=>{localStorage.setItem("skill-gomoku-settings",JSON.stringify(settings));document.documentElement.classList.toggle("reduce-motion",settings.reducedMotion)},[settings]);
  useEffect(()=>{if(screen!=="game")return;if(game.phase==="aiThinking"){const id=setTimeout(()=>dispatch({type:"AI_ACT"}),520);return()=>clearTimeout(id)}if(game.phase==="reactionWindow"&&game.pendingSkill?.player===0){const id=setTimeout(()=>dispatch({type:"REACTION",use:game.difficulty!=="easy"}),420);return()=>clearTimeout(id)}},[game.phase,game.pendingSkill,game.difficulty,screen]);
  useEffect(()=>{if(screen!=="game"||!game.animation||game.result)return;const id=setTimeout(()=>dispatch({type:"CLEAR_ANIMATION"}),settings.reducedMotion?80:650);return()=>clearTimeout(id)},[game.animation,game.result,screen,settings.reducedMotion]);
  useEffect(()=>{if(game.lastMove)playTone("stone",settings);},[game.lastMove]);
  useEffect(()=>{if(game.skillHistory.length)playTone("skill",settings);},[game.skillHistory.length]);
  useEffect(()=>{if(game.result){playTone("win",settings);const record={date:new Date().toLocaleDateString(),winner:game.result.winner===null?"平局":characters.find(c=>c.id===game.players[game.result!.winner!].character)?.name,turns:Math.ceil(game.turn/2),happy:game.stats.maxHappy};const records=load<unknown[]>("skill-gomoku-records",[]);localStorage.setItem("skill-gomoku-records",JSON.stringify([record,...records].slice(0,12)));if(mode==="story"&&chapter===unlocked&&unlocked<4){setUnlocked(unlocked+1);localStorage.setItem("skill-gomoku-progress",String(unlocked+1));}}},[game.result]);
  function choose(action:HomeAction){if(["story","free","pure","local"].includes(action)){const m=action as GameMode;setMode(m);if(m==="story"){setSelected("zhang");setChapter(Math.min(unlocked,4))}setEnvironment(m!=="pure");setScreen("select")}else setModal(action)}
  function actuallyStart(){const opponent=mode==="story"?storyChapters[chapter-1].opponent:selected==="principal"?"ziqi":"principal";const fresh=createGame({mode,playerCharacter:selected,opponentCharacter:opponent,difficulty,environment,chaos,chapter});dispatch({type:"LOAD",state:fresh});setScreen("game")}
  const line=storyChapters[chapter-1]?.intro[dialogueIndex];
  return <>{screen==="home"&&<Home onAction={choose} unlocked={unlocked}/>} {screen==="select"&&<CharacterSelect mode={mode} selected={selected} setSelected={setSelected} difficulty={difficulty} setDifficulty={setDifficulty} environment={environment} setEnvironment={setEnvironment} chaos={chaos} setChaos={setChaos} chapter={chapter} setChapter={setChapter} unlocked={unlocked} onStart={()=>{setDialogueIndex(0);if(mode==="story"&&settings.dialogue)setScreen("dialogue");else actuallyStart()}} onBack={()=>setScreen("home")}/>} {screen==="dialogue"&&<main className="dialogue-screen" onClick={()=>{if(dialogueIndex<storyChapters[chapter-1].intro.length-1)setDialogueIndex(dialogueIndex+1);else actuallyStart()}}><div className="curtain left"/><div className="curtain right"/><section><small>第 {chapter} 章 · {storyChapters[chapter-1].title}</small><div className="dialogue-portrait">{characters.find(c=>c.name===line?.[0])?.icon??"?"}</div><h2>{line?.[0]}</h2><p>{line?.[1]}</p><button>{dialogueIndex<storyChapters[chapter-1].intro.length-1?"继续":"开始对局"} →</button><em>点击任意位置可加速</em></section></main>} {screen==="game"&&<GameView state={game} dispatch={dispatch} onHome={()=>setScreen("home")}/>} {modal&&<InfoModal type={modal} settings={settings} setSettings={setSettings} onClose={()=>setModal(null)}/>}</>;
}

function InfoModal({type,settings,setSettings,onClose}:{type:HomeAction;settings:Settings;setSettings:(s:Settings)=>void;onClose:()=>void}){
  const titles={characters:"角色图鉴",skills:"技能图鉴",settings:"礼堂设置",records:"历史战绩",credits:"制作说明",story:"",free:"",pure:"",local:""};const records=load<{date:string;winner:string;turns:number;happy:number}[]>("skill-gomoku-records",[]);
  return <div className="modal-backdrop" onPointerDown={(e)=>e.target===e.currentTarget&&onClose()}><section className="info-modal"><header><div><small>校务公开</small><h1>{titles[type]}</h1></div><button onClick={onClose}>×</button></header>{type==="characters"&&<div className="catalog-grid">{characters.map(c=><article key={c.id} style={{"--accent":c.accent} as React.CSSProperties}><span>{c.icon}</span><h2>{c.name}</h2><p>{c.role}</p><small>{c.passive}</small></article>)}</div>}{type==="skills"&&<div className="skill-catalog">{skillList.map(s=><article key={s.id}><b>{s.name}</b><em>{s.cost} 技能值</em><p>{s.rules}</p></article>)}</div>}{type==="settings"&&<div className="settings-list"><label><span>原创音效</span><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/></label><label><span>音量</span><input type="range" min="0" max="1" step=".05" value={settings.volume} onChange={e=>setSettings({...settings,volume:Number(e.target.value)})}/></label><label><span>剧情对白</span><input type="checkbox" checked={settings.dialogue} onChange={e=>setSettings({...settings,dialogue:e.target.checked})}/></label><label><span>减少动态效果</span><input type="checkbox" checked={settings.reducedMotion} onChange={e=>setSettings({...settings,reducedMotion:e.target.checked})}/></label></div>}{type==="records"&&<div className="records">{records.length?records.map((r,i)=><article key={i}><b>{r.winner}</b><span>{r.turns} 回合 · 快乐 {r.happy}</span><small>{r.date}</small></article>):<p>暂无战绩。档案室正在认真保持空白。</p>}</div>}{type==="credits"&&<div className="credits"><p>《技能五子棋学校》是一款纯前端荒诞策略游戏。棋盘、人物、特效与音效均由代码生成，不依赖远程素材。</p><p>核心原则：五连规则必须认真，解释规则的人可以不认真。</p><p>支持键鼠、触摸、减少动态效果与本机存档。</p></div>}</section></div>
}
